In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
path = 'C:/Users/DEVENDRA/Desktop/ml_database_7/credit_fraud/creditcard.csv'
df = pd.read_csv(path)

In [3]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...         V21       V22       V23       V24  \
0  0.098698  0.363787  ...   -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425  ...   -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  ...    0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024  ...   -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  ...   -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4 -0.206010  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [5]:
df.shape

(284807, 31)

In [6]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [ ]:
#### Under Sampling

In [8]:
x = df.drop('Class', axis = 1)
y = df['Class']

In [10]:
y.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [11]:
x.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9   ...         V20       V21       V22       V23  \
0  0.098698  0.363787   ...    0.251412 -0.018307  0.277838 -0.110474   
1  0.085102 -0.255425   ...   -0.069083 -0.225775 -0.638672  0.101288   
2  0.247676 -1.514654   ...    0.524980  0.247998  0.771679  0.909412   
3  0.377436 -1.387024   ...   -0.208038 -0.108300  0.005274 -0.190321   
4 -0.270533  0.817739   ...    0.408542 -0.009431  0.798278 -0.137458   

        V24       V25       V26       V27       V28  Amount  
0  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62  
1 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69  
2 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66  
3 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50  
4  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99  

[5 rows x 30 columns]

### Cross Validation Like kfold and hyperparameter tunning

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

In [19]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = 0.7)

In [17]:
log_class = LogisticRegression()
grid = {'C':10.0**np.arange(-2,3),
       'penalty':['l1','l2']}
cv = KFold(n_splits=5, random_state = None, shuffle = False)

In [21]:
clf = GridSearchCV(log_class, grid,cv=cv, n_jobs = -1, scoring='f1_macro')
clf.fit(x_train, y_train)

C:\Users\DEVENDRA\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [25]:
y_pred = clf.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85260    35]
 [   52    96]]
0.9989817773252344
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85295
           1       0.73      0.65      0.69       148

    accuracy                           1.00     85443
   macro avg       0.87      0.82      0.84     85443
weighted avg       1.00      1.00      1.00     85443



In [30]:
## class weight
class_we = dict({0:1,1:100})

In [31]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(class_weight=class_we)
classifier.fit(x_train, y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [32]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85291     4]
 [   27   121]]
0.9996371850239341
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85295
           1       0.97      0.82      0.89       148

    accuracy                           1.00     85443
   macro avg       0.98      0.91      0.94     85443
weighted avg       1.00      1.00      1.00     85443



In [28]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85289     6]
 [   25   123]]
0.9996371850239341
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85295
           1       0.95      0.83      0.89       148

    accuracy                           1.00     85443
   macro avg       0.98      0.92      0.94     85443
weighted avg       1.00      1.00      1.00     85443



## UnderSampling

In [36]:
from imblearn.under_sampling import NearMiss
from collections import Counter
ns = NearMiss(0.8)
x_train_ns, y_train_ns = ns.fit_sample(x_train, y_train)
print("the number of class before fit{}".format(Counter(y_train)))
print("the number of class before fit{}".format(Counter(y_train_ns)))

C:\Users\DEVENDRA\Anaconda3\lib\site-packages\imblearn\utils\_validation.py:638: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning)


the number of class before fitCounter({0: 199020, 1: 344})
the number of class before fitCounter({0: 430, 1: 344})


In [44]:
(80/100)*430

344.0

In [45]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(x_train_ns, y_train_ns)

RandomForestClassifier()

In [46]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[62996 22299]
 [    6   142]]
0.7389487728661213
              precision    recall  f1-score   support

           0       1.00      0.74      0.85     85295
           1       0.01      0.96      0.01       148

    accuracy                           0.74     85443
   macro avg       0.50      0.85      0.43     85443
weighted avg       1.00      0.74      0.85     85443



### Over sampling

In [50]:
from imblearn.over_sampling import RandomOverSampler
from collections import Counter
ns = RandomOverSampler(0.5)
x_train_os, y_train_os = ns.fit_sample(x_train, y_train)
print("the number of class before fit{}".format(Counter(y_train)))
print("the number of class before fit{}".format(Counter(y_train_os)))

C:\Users\DEVENDRA\Anaconda3\lib\site-packages\imblearn\utils\_validation.py:638: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning)


the number of class before fitCounter({0: 199020, 1: 344})
the number of class before fitCounter({0: 199020, 1: 99510})


In [51]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(x_train_os, y_train_os)

RandomForestClassifier()

In [52]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85290     5]
 [   24   124]]
0.9996605924417448
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85295
           1       0.96      0.84      0.90       148

    accuracy                           1.00     85443
   macro avg       0.98      0.92      0.95     85443
weighted avg       1.00      1.00      1.00     85443



### SMOTETomek

In [54]:
from imblearn.combine import SMOTETomek

In [56]:
sm = SMOTETomek(0.5)
x_train_os, y_train_os = sm.fit_sample(x_train, y_train)
print("the number of class before fit{}".format(Counter(y_train)))
print("the number of class before fit{}".format(Counter(y_train_os)))

C:\Users\DEVENDRA\Anaconda3\lib\site-packages\imblearn\utils\_validation.py:638: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning)


the number of class before fitCounter({0: 199020, 1: 344})
the number of class before fitCounter({0: 198174, 1: 98664})


In [57]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(x_train_os, y_train_os)

RandomForestClassifier()

In [64]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85279    16]
 [   18   130]]
0.999602073897218
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85295
           1       0.89      0.88      0.88       148

    accuracy                           1.00     85443
   macro avg       0.95      0.94      0.94     85443
weighted avg       1.00      1.00      1.00     85443



### Ensemble technique

In [61]:
from imblearn.ensemble import EasyEnsembleClassifier

In [62]:
easy = EasyEnsembleClassifier()
easy.fit(x_train, y_train)

EasyEnsembleClassifier()

In [65]:
y_pred = easy.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[81671  3624]
 [    7   141]]
0.9575038329646665
              precision    recall  f1-score   support

           0       1.00      0.96      0.98     85295
           1       0.04      0.95      0.07       148

    accuracy                           0.96     85443
   macro avg       0.52      0.96      0.53     85443
weighted avg       1.00      0.96      0.98     85443

